# Generated by Django 3.2.5 on 2021-07-29 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_wine_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='date_consumed',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='wine',
            name='img',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='wine',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wine',
            name='rating',
            field=models.FloatField(default=5),
        ),
    ]
